replicaCount: 2

image:
  repository: somu123/order-service
  pullPolicy: IfNotPresent
  tag: latest

service:
  name: order-service
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
